[package]
name = "static_web_server"
version = "0.5.0"
authors = ["Mark Gitthens"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]